[ARGS]
FILENAME = "../../on_line/lib/Modules/"
CONV_TYPE = "conv2d"
REPRODUCE = 1

[INPUT_PARAMS]
IM_DIM_H = 96
IM_DIM_W = 96
IM_IN_CH = 3
BIT = 8

[CONV]
CONV_IN_CH = 3
CONV_KER_DIM_H = 3
CONV_KER_DIM_W = 3
CONV_OUT_CH = 16
CONV_STRIDE_W = 2
CONV_STRIDE_H = 2
PADMODE = 1
DILATION = 1
GROUPS = 1
BIAS = 1

[OPTIMIZING]
TCM = 1
CACHE = 1
PIPELINING = 1
LOOP_UNROLLING = 1
WEIGHT_INTERLEAVING = "RGB"
IM2COL = 1
