[ARGS]
FILENAME = 'symmetric'
CONV_TYPE = 'conv2d' # conv2d, conv2d_dw, conv2d_pw, conv2d_dw_pw
REPRODUCE = 1

[INPUT_PARAMS] # HWC
IM_DIM_H = 32
IM_DIM_W = 32
IM_IN_CH = 3
BIT = 8
[CONV] # NHWC
CONV_IN_CH = "${INPUT_PARAMS.IM_IN_CH}"
CONV_KER_DIM_H = 3
CONV_KER_DIM_W = 3
CONV_OUT_CH = 64
CONV_STRIDE_W=1
CONV_STRIDE_H = 1
CONV_PADDING_H = 1
CONV_PADDING_W = 1
PADDING = 0 # SAME, VALID
PADMODE = "zeros"
DILATION = 1
GROUPS = 1
BIAS = 1
[OPTIMIZING]
TCM = 0 # TCM 여부
CACHE = 1 # Cache 사용 여부
WEIGHT_INTERLEAVING = 'RGB' # Loop Interleaving 사용 여부(RGB or EVEN)
IM2COL = 1 # Im2Col 사용 여부