[ARGS]
FILENAME = "./symmetric"
CONV_TYPE = "conv2d"
REPRODUCE = 1

[INPUT_PARAMS]
IM_DIM_H = 32
IM_DIM_W = 32
IM_IN_CH = 3
BIT = 8

[CONV]
CONV_IN_CH = 3
CONV_KER_DIM_H = 3
CONV_KER_DIM_W = 3
CONV_OUT_CH = 32
CONV_STRIDE_W = 1
CONV_STRIDE_H = 1
PADMODE = 1
DILATION = 1
GROUPS = 1
BIAS = 1

[OPTIMIZING]
TCM = 0
CACHE = 1
WEIGHT_INTERLEAVING = "RGB"
IM2COL = 1
